sudo: required

language: bash

services:
  - docker

before_script:
  - export APP_IMAGE=keboola-component
  - docker -v
  - docker build -t $APP_IMAGE .
  - docker run -e KBC_TEST_TOKEN -e KBC_TEST_WRITE_TOKEN -e KBC_TEST_URL -e KBC_TEST_BUCKET $APP_IMAGE composer ci

  # push test image to ECR
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag $APP_IMAGE:latest $REPOSITORY:test
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:test
  - docker pull quay.io/keboola/syrup-cli:latest


script:
  # run test job inside KBC
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG_ID test

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: ITJU0Weopth+EBK6uFn2GLalknoJrVU57u4gijoYOGcaYOEvcM0yFbszlx6CbXFV7GYHqefj+vFoxyyKaskWR90MMHOPIhrj25jvKM5a4+1sXSFOZeso04jx4QxD9SSCMunVgNC95nVuTcJvwJRqWOHs9taiDDld3QCkQ1xtA5BSvKcLr5r879wqKF07hAgRzwDcndqkFFXjH1NL95LdeLoWtUHm/dxUMrsEs36/KmdgNkn2agMqOMZg56MytFIfo7f9oFS5PnXTR/EnqlfCoNvtl0iog8R9G9iXUhbTNznWY0Vs199PmUHbyB8ynVVPgZ+GSt7DfvdYubGfAlSumMNOir7ogP5UGnwt9a9dNqoTV5ICICjyxU1+4PkKVV11KogK1i1CE6oAr9KgzwNVZHwvfjycDvyaodyLEKKr29vHML22LojQLGImMz5h/YrflHIZmzDtv5Cj9kwmDzOqjywTFqx+pEMBarAWBU95BGvOuIUK3ltqQhXtm+7tsAOCYlYN0OCHS1qaatlkvginbsNeSO5vfkm/o5g/O+bWSIKXSpEgL8iRI7K9TOOXZ02Cmv3bZuYkxw5qCpn4FRgtS0sZX58xwKz8Vg1SITjXWjsj20FgG65+uP8wEoqmgbYtWiybkSnC8y8YTDAc7jzFSsKUurjuyOq8/u4x0VCGqRs=
  email: false
